"use client";

import { motion, useScroll, useTransform, AnimatePresence } from "motion/react";
import React, { useRef, useState } from "react";
import Image from "next/image";

const AnthropicEmailVisual = () => (
  <div className="w-full h-full flex font-anthropic-sans bg-white">
    {/* Left Sidebar (Mailboxes) - Completely Borderless */}
    <div className="w-[140px] md:w-[200px] bg-[#faf9f7] hidden sm:flex flex-col p-6 md:p-8 gap-5 shadow-[inset_-10px_0_20px_rgba(0,0,0,0.02)] relative z-10">
       <div className="w-full h-8 bg-stone-200/60 rounded-lg mb-6" />
       {[1,2,3,4,5,6,7].map(i => <div key={i} className="w-full h-3.5 bg-stone-100 rounded-full" />)}
    </div>
    
    {/* Main Email Area - Edge to Edge, zoomed in */}
    <div className="flex-1 flex flex-col h-full overflow-hidden p-8 md:p-14 relative bg-white">
      <div className="absolute top-0 right-0 w-48 h-48 bg-gradient-to-bl from-clay/5 to-transparent rounded-bl-full pointer-events-none" />
      
      {/* Header */}
      <div className="flex flex-col gap-5 pb-8 mb-8 relative">
        <div className="absolute bottom-0 left-0 w-full h-[1px] bg-gradient-to-r from-stone-200 to-transparent" />
        <div className="flex items-center gap-5">
           <div className="w-12 h-12 rounded-full bg-slate-800 text-white flex items-center justify-center font-bold text-[14px] tracking-widest shadow-md">CE</div>
           <div className="flex flex-col gap-1.5">
             <div className="text-[16px] font-bold text-slate-dark leading-none">Client Enterprise</div>
             <div className="text-[14px] text-slate-dark/50 leading-none">client@enterprise.com</div>
           </div>
        </div>
        <div className="text-[24px] md:text-[32px] font-anthropic-serif font-semibold text-slate-dark mt-2 leading-tight">
          Q4 Sync: Decisions, Action Items & Next Steps
        </div>
        
        <motion.div initial={{opacity:0, scale:0.95}} animate={{opacity:1, scale:1}} transition={{delay:0.3}} className="inline-flex w-fit items-center gap-2 text-clay text-[12px] font-bold uppercase tracking-widest bg-clay/5 px-4 py-2 rounded-full shadow-sm mt-2">
          <span className="w-2.5 h-2.5 rounded-full bg-clay animate-pulse" /> Auto-Generated by Smriti
        </motion.div>
      </div>

      {/* Body Content (Dense) */}
      <div className="flex flex-col gap-5">
         <div className="h-3.5 w-full bg-stone-100 rounded-full" />
         <div className="h-3.5 w-11/12 bg-stone-100 rounded-full" />
         <div className="h-3.5 w-4/5 bg-stone-100 rounded-full mb-6" />
         
         {/* Embedded Action Items Checklist - Borderless with soft shadow */}
         <div className="bg-[#faf9f7] shadow-[0_8px_30px_rgba(0,0,0,0.03)] rounded-2xl p-6 md:p-8 flex flex-col gap-5 relative overflow-hidden">
            <div className="absolute left-0 top-0 bottom-0 w-1.5 bg-clay" />
            <div className="text-[13px] font-bold text-slate-dark tracking-widest uppercase mb-2">Key Action Items</div>
            
            <div className="flex items-start gap-4">
              <div className="w-5 h-5 rounded-md flex items-center justify-center bg-clay/10 mt-0.5"><div className="w-2.5 h-2.5 bg-clay rounded-sm"/></div>
              <div className="flex flex-col gap-2.5 flex-1">
                 <div className="h-4 w-3/4 bg-stone-300/80 rounded-full" />
                 <div className="h-2.5 w-1/2 bg-stone-200 rounded-full" />
              </div>
            </div>

            <div className="flex items-start gap-4">
              <div className="w-5 h-5 rounded-md flex items-center justify-center bg-white shadow-sm mt-0.5" />
              <div className="flex flex-col gap-2.5 flex-1">
                 <div className="h-4 w-5/6 bg-stone-300/80 rounded-full" />
                 <div className="h-2.5 w-1/3 bg-stone-200 rounded-full" />
              </div>
            </div>
         </div>
      </div>
    </div>
  </div>
);

const AnthropicMemoryVisual = () => (
  <div className="w-full h-full bg-white flex flex-col font-anthropic-sans overflow-hidden">
    {/* Top Header / Search - Massive, Edge to Edge */}
    <div className="p-8 md:p-14 flex flex-col gap-8 bg-[#faf9f7] shadow-sm relative z-10 border-none">
       <div className="flex items-center gap-4">
          <div className="w-full bg-white rounded-full shadow-[0_12px_40px_rgba(0,0,0,0.04)] px-6 py-5 flex items-center gap-5">
             <svg className="w-6 h-6 text-clay" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
             <span className="text-[18px] font-anthropic-serif italic text-slate-dark/70">"What did we promise Microsoft in Q3 regarding SSO?"</span>
          </div>
       </div>
       <div className="flex gap-4 overflow-hidden">
          <span className="px-5 py-2 rounded-full bg-clay text-white text-[12px] font-bold tracking-widest uppercase shadow-md">All Sources (12)</span>
          <span className="px-5 py-2 rounded-full bg-white text-slate-dark/60 text-[12px] font-bold tracking-widest uppercase shadow-sm">Meetings (4)</span>
          <span className="px-5 py-2 rounded-full bg-white text-slate-dark/60 text-[12px] font-bold tracking-widest uppercase shadow-sm hidden sm:flex">Emails (8)</span>
       </div>
    </div>
    
    {/* Dense Results List - Edge to Edge */}
    <div className="flex-1 p-8 md:p-14 flex flex-col gap-6 relative bg-white border-none">
       {/* Result 1 (Highlighted) - Borderless soft shadow */}
       <motion.div initial={{opacity:0, y:10}} animate={{opacity:1, y:0}} transition={{delay:0.3}} className="w-full bg-white rounded-[24px] p-8 shadow-[0_20px_50px_rgba(200,100,80,0.08)] relative overflow-hidden">
          <div className="absolute top-0 left-0 w-1.5 h-full bg-clay" />
          <div className="flex items-center justify-between mb-5">
             <div className="text-[12px] font-bold text-clay uppercase tracking-[0.2em] flex items-center gap-3">
               <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>
               Q3 Review • Oct 14
             </div>
             <div className="flex -space-x-3">
               <div className="w-8 h-8 rounded-full border-2 border-white bg-slate-800 shadow-sm" />
               <div className="w-8 h-8 rounded-full border-2 border-white bg-clay shadow-sm" />
             </div>
          </div>
          <div className="text-[16px] md:text-[18px] text-slate-dark leading-[1.6]">
             We committed to delivering the <span className="bg-manilla/80 px-2 py-0.5 rounded font-medium border-b border-manilla-dark/30 shadow-sm">Enterprise SSO integration</span> by the end of Q4 to unblock their 50k seat rollout.
          </div>
       </motion.div>

       {/* Result 2 - Borderless soft flat */}
       <motion.div initial={{opacity:0, y:10}} animate={{opacity:1, y:0}} transition={{delay:0.5}} className="w-full bg-[#faf9f7] rounded-[24px] p-8 opacity-80">
          <div className="flex items-center justify-between mb-5">
             <div className="text-[12px] font-bold text-slate-dark/40 uppercase tracking-[0.2em] flex items-center gap-3">
               <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>
               Follow-up Thread • Sep 22
             </div>
          </div>
          <div className="text-[16px] md:text-[18px] text-slate-dark/70 leading-[1.6]">
             "Can we get an update on the <span className="bg-stone-200/50 px-2 py-0.5 rounded font-medium shadow-sm">SSO timeline</span>? We need to plan our Q1 migration."
          </div>
       </motion.div>

       <div className="absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-white to-transparent pointer-events-none" />
    </div>
  </div>
);

const AnthropicActionsVisual = () => (
  <div className="w-full h-full bg-white flex font-anthropic-sans">
     {/* Left: Streaming Transcript - Edge to Edge Background */}
     <div className="flex-1 bg-[#faf9f7] p-8 md:p-14 flex flex-col gap-8 opacity-90 relative shadow-[inset_-20px_0_40px_rgba(0,0,0,0.02)] border-none">
        <div className="flex items-center gap-3 border-b border-stone/10 pb-6 mb-2">
           <div className="w-10 h-10 rounded-full bg-white shadow-sm flex items-center justify-center text-[12px] font-bold text-slate-dark border border-stone/10">AI</div>
           <div className="text-[16px] font-bold text-slate-dark">Real-time Transcript</div>
        </div>
        
        <div className="text-[15px] leading-[1.8] text-slate-dark/80 font-medium flex flex-col gap-6 relative z-10">
           <p><span className="font-bold text-slate-dark">Alex (Client):</span> Yeah, so if we can get those updated API docs by tomorrow, that unblocks our eng team.</p>
           <p><span className="font-bold text-slate-dark">Sarah (You):</span> Sounds good. <span className="bg-clay/10 px-2 py-1 rounded text-slate-dark shadow-[0_0_15px_rgba(200,100,80,0.15)] border-b border-clay/20">I'll send the API docs over by EOD tomorrow.</span></p>
           <p><span className="font-bold text-slate-dark opacity-50">Alex:</span> Also need to review the Q3 security audit.</p>
        </div>
        <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-[#faf9f7] to-transparent z-20 pointer-events-none" />
     </div>

     {/* Right: Extracted Action Items */}
     <div className="flex-1 flex flex-col gap-6 relative p-8 md:p-14 border-none bg-white">
        <div className="flex items-center justify-between border-b border-stone/10 pb-6 mb-2">
           <div className="text-[12px] font-bold text-slate-dark/40 uppercase tracking-[0.2em]">Captured Actions</div>
           <div className="flex items-center gap-2">
             <span className="w-2.5 h-2.5 rounded-full bg-clay animate-pulse shadow-sm" />
             <span className="text-[11px] font-bold text-clay uppercase tracking-widest">Live</span>
           </div>
        </div>
        
        <motion.div initial={{opacity:0, x:20}} animate={{opacity:1, x:0}} transition={{delay:0.3}} className="bg-white rounded-2xl p-6 shadow-[0_20px_50px_rgba(200,100,80,0.06)] relative overflow-hidden group">
           <div className="absolute top-0 right-0 w-24 h-24 bg-gradient-to-bl from-clay/5 to-transparent rounded-bl-full" />
           <div className="absolute left-0 top-0 bottom-0 w-1.5 bg-clay" />
           
           <div className="flex items-start gap-4">
             <div className="w-5 h-5 rounded border border-clay/30 bg-clay/5 flex-shrink-0 mt-0.5 shadow-sm" />
             <div className="text-[16px] font-medium text-slate-dark leading-[1.4]">Send updated API docs to Alex</div>
           </div>
           <div className="mt-6 flex items-center justify-between">
             <div className="flex items-center gap-2">
                <div className="w-7 h-7 rounded-full bg-slate-800 text-white flex items-center justify-center text-[9px] font-bold shadow-sm">ME</div>
             </div>
             <span className="text-[11px] text-clay font-bold tracking-widest uppercase bg-clay/5 px-3 py-1.5 rounded-md shadow-sm">Due Tomorrow</span>
           </div>
        </motion.div>

        <motion.div initial={{opacity:0, x:20}} animate={{opacity:1, x:0}} transition={{delay:0.6}} className="bg-[#faf9f7] rounded-2xl p-6 opacity-60">
           <div className="flex items-start gap-4">
             <div className="w-5 h-5 rounded border border-stone/20 bg-white flex-shrink-0 mt-0.5" />
             <div className="text-[16px] font-medium text-slate-dark/70 leading-[1.4]">Schedule Q3 security audit review</div>
           </div>
        </motion.div>
     </div>
  </div>
);

const AnthropicSecurityVisual = () => (
  <div className="w-full h-full bg-[#fdfaf6] p-0 flex flex-col items-center justify-center font-anthropic-sans relative overflow-hidden">
     {/* Dense Grid Background - Edge to edge */}
     <div className="absolute inset-0 bg-[linear-gradient(to_right,#e5e5e5_1px,transparent_1px),linear-gradient(to_bottom,#e5e5e5_1px,transparent_1px)] bg-[size:32px_32px] opacity-40" />
     <div className="absolute inset-0 bg-gradient-to-b from-[#fdfaf6]/50 via-transparent to-[#fdfaf6]/50 pointer-events-none" />
     
     {/* Massive Architecture diagram */}
     <div className="flex flex-col gap-10 w-full max-w-[800px] relative z-10 px-8">
        <div className="flex items-center justify-between w-full px-12">
           <div className="flex flex-col items-center gap-3 opacity-40">
             <div className="w-20 h-16 rounded-xl flex items-center justify-center bg-white shadow-sm border border-stone/10"><span className="text-[12px] font-bold">Tenant A</span></div>
             <div className="h-12 w-[2px] bg-stone-300 border-l border-dashed" />
           </div>
           <div className="flex flex-col items-center gap-3 opacity-40">
             <div className="w-20 h-16 rounded-xl flex items-center justify-center bg-white shadow-sm border border-stone/10"><span className="text-[12px] font-bold">Tenant B</span></div>
             <div className="h-12 w-[2px] bg-stone-300 border-l border-dashed" />
           </div>
           <div className="flex flex-col items-center gap-3 opacity-40">
             <div className="w-20 h-16 rounded-xl flex items-center justify-center bg-white shadow-sm border border-stone/10"><span className="text-[12px] font-bold">Tenant C</span></div>
             <div className="h-12 w-[2px] bg-stone-300 border-l border-dashed" />
           </div>
        </div>

        <motion.div initial={{y:10}} animate={{y:0}} className="w-full bg-white rounded-[32px] shadow-[0_40px_80px_rgba(200,100,80,0.06)] relative flex flex-col p-10 border-none">
           <div className="absolute -top-4 left-1/2 -translate-x-1/2 bg-clay text-white text-[12px] font-bold uppercase tracking-[0.2em] px-6 py-2.5 rounded-full shadow-lg flex items-center gap-3">
             <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" /></svg>
             Isolated Vaults
           </div>
           
           <div className="grid grid-cols-3 gap-6 mt-6">
              {/* Isolated DB 1 */}
              <div className="col-span-1 bg-white shadow-[0_10px_30px_rgba(0,0,0,0.03)] rounded-2xl p-6 flex flex-col items-center text-center gap-3 relative overflow-hidden group">
                 <div className="absolute inset-0 bg-clay/5 opacity-0 group-hover:opacity-100 transition-opacity" />
                 <svg className="w-8 h-8 text-clay" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4" /></svg>
                 <span className="text-[12px] font-bold text-slate-dark uppercase tracking-widest mt-2">AES-256</span>
              </div>
              <div className="col-span-1 bg-[#faf9f7] rounded-2xl p-6 flex flex-col items-center text-center gap-3 opacity-60">
                 <svg className="w-8 h-8 text-stone-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4" /></svg>
                 <span className="text-[12px] font-bold text-slate-dark uppercase tracking-widest mt-2">Encrypted</span>
              </div>
              <div className="col-span-1 bg-[#faf9f7] rounded-2xl p-6 flex flex-col items-center text-center gap-3 opacity-60">
                 <svg className="w-8 h-8 text-stone-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4" /></svg>
                 <span className="text-[12px] font-bold text-slate-dark uppercase tracking-widest mt-2">Encrypted</span>
              </div>
           </div>
           
           <div className="w-full flex justify-between mt-10 pt-6 border-t border-stone-200/50 px-2">
              <span className="text-[11px] text-slate-dark/60 font-bold uppercase tracking-widest">SOC2 Type II Certified</span>
              <span className="text-[11px] text-slate-dark/60 font-bold uppercase tracking-widest flex items-center gap-2"><div className="w-2 h-2 bg-green-500 rounded-full"/> Zero Training on Customer Data</span>
           </div>
        </motion.div>
     </div>
  </div>
);

const features = [
  {
    num: "01",
    title: "Email Automation",
    desc: "Meeting reports sent directly to your clients' mailboxes the moment you hang up. Smriti handles the formatting, tone, and delivery automatically.",
    color: "from-blue-400 to-cyan-300",
    visual: <AnthropicEmailVisual />
  },
  {
    num: "02",
    title: "Global Memory",
    desc: "Query and chat with all your past meetings instantly. Ask broad questions across your entire customer base or drill down into specific commitments made months ago.",
    color: "from-purple-400 to-fuchsia-300",
    visual: <AnthropicMemoryVisual />
  },
  {
    num: "03",
    title: "Action Items",
    desc: "Instantly extract next steps and commitments from every call. Our proprietary models are fine-tuned to distinguish passing remarks from concrete promises.",
    color: "from-green-400 to-emerald-300",
    visual: <AnthropicActionsVisual />
  },
  {
    num: "04",
    title: "Enterprise Security",
    desc: "Multi-tenant architecture ensuring your data is completely isolated and secure. We never use your customer data to train our foundational models.",
    color: "from-clay-deep to-clay",
    visual: <AnthropicSecurityVisual />
  }
];

export function PremiumFeatures() {
  const [activeFeature, setActiveFeature] = useState(0);

  return (
    <section id="capabilities" className="w-full max-w-[1400px] mx-auto px-6 py-[120px] flex flex-col relative z-10 perspective-[2000px]">
      
      {/* Massive Ambient Background Glow */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[120vw] h-[120vh] pointer-events-none flex items-center justify-center opacity-30 mix-blend-color-dodge">
        <motion.div 
           key={activeFeature}
           initial={{ opacity: 0, scale: 0.8 }}
           animate={{ opacity: 1, scale: 1 }}
           transition={{ duration: 1.5, ease: "easeOut" }}
           className={`w-[800px] h-[800px] rounded-full bg-gradient-to-br ${features[activeFeature].color} blur-[200px]`}
        />
      </div>

      <div className="flex flex-col items-center text-center mb-16 md:mb-[120px] relative z-20">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="inline-flex items-center gap-3 px-5 py-2.5 rounded-full border border-stone/30 bg-white/40 backdrop-blur-xl mb-8 shadow-[0_8px_30px_rgba(0,0,0,0.04)]"
        >
          <span className="w-2 h-2 rounded-full bg-clay animate-[pulse_1.5s_ease-in-out_infinite] shadow-[0_0_10px_rgba(200,100,80,0.8)]" />
          <span className="font-anthropic-sans text-[11px] font-bold uppercase tracking-[0.25em] text-slate-dark/70">
            Platform Capabilities
          </span>
        </motion.div>
        <motion.h2 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.1 }}
          className="font-anthropic-serif text-[64px] md:text-[84px] leading-[1.05] tracking-tight text-slate-dark"
        >
          Intelligence that <br />
          <em className="italic font-normal text-transparent bg-clip-text bg-gradient-to-r from-clay-deep via-orange-400 to-clay-deep animate-[shimmer_4s_infinite] bg-[length:200%_auto]">
            works for you.
          </em>
        </motion.h2>
      </div>
      
      {/* Scroll-Spy Interactive Tabs Layout */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-8 lg:gap-16 w-full relative z-20">
        
        {/* Left Side: Tall Scrolling List of Tabs */}
        <div className="md:col-span-5 flex flex-col shrink-0 pb-[30vh] md:pb-[40vh] relative z-10 pt-[5vh]">
          {features.map((feature, index) => (
            <motion.div
              key={feature.num}
              onViewportEnter={() => setActiveFeature(index)}
              viewport={{ margin: "-45% 0px -45% 0px" }}
              className={`flex flex-col justify-center min-h-[30vh] lg:min-h-[45vh] transition-all duration-700 relative group cursor-pointer ${activeFeature === index ? 'opacity-100 scale-100' : 'opacity-40 scale-[0.98]'}`}
            >
              {/* Active Tab Highlight Background (Light Mode) */}
              {activeFeature === index && (
                <motion.div 
                  layoutId="activeTabBgLight"
                  className="absolute inset-0 -mx-6 bg-white/60 backdrop-blur-md border border-stone/20 rounded-[32px] shadow-[0_8px_30px_rgba(0,0,0,0.03)]"
                  initial={false}
                  transition={{ type: "spring", stiffness: 300, damping: 30 }}
                />
              )}

              <div className="relative z-10 text-left py-8 px-4 rounded-3xl">
                <div className="flex items-center gap-6 mb-5">
                   <motion.div 
                     animate={{ 
                       backgroundColor: activeFeature === index ? "#c86450" : "transparent",
                       color: activeFeature === index ? "#fff" : "#2e2e2d",
                       borderColor: activeFeature === index ? "transparent" : "rgba(46,46,45,0.15)"
                     }}
                     className="w-12 h-12 rounded-full flex items-center justify-center font-anthropic-sans text-[14px] font-bold transition-colors duration-500 shadow-sm border border-transparent shrink-0"
                   >
                     {feature.num}
                   </motion.div>
                   <h3 className={`font-anthropic-serif text-[32px] lg:text-[36px] tracking-tight transition-colors duration-500 ${activeFeature === index ? 'text-slate-dark' : 'text-slate-dark/50'}`}>
                     {feature.title}
                   </h3>
                </div>
                
                <div className="overflow-hidden">
                  <AnimatePresence>
                    {activeFeature === index && (
                      <motion.p
                        initial={{ opacity: 0, y: 10, height: 0 }}
                        animate={{ opacity: 1, y: 0, height: "auto" }}
                        exit={{ opacity: 0, y: -10, height: 0 }}
                        transition={{ duration: 0.4, ease: "easeOut" }}
                        className="font-anthropic-sans text-[16px] lg:text-[17px] leading-[1.6] text-slate-dark/70 pt-2 pl-[72px]"
                      >
                        {feature.desc}
                      </motion.p>
                    )}
                  </AnimatePresence>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Right Side: Sticky Massive Ivory Visualizer */}
        <div className="md:col-span-7 w-full relative perspective-[2000px] min-w-0">
          <div className="sticky top-[15vh] lg:top-[12.5vh] h-[40vh] md:h-[50vh] lg:h-[75vh] min-h-[350px] md:min-h-[400px] lg:min-h-[600px] bg-white rounded-[32px] shadow-[0_30px_100px_rgba(0,0,0,0.08)] overflow-hidden flex items-center justify-center group z-20 [transform-style:preserve-3d] border-none">
            
            <AnimatePresence mode="wait">
              <motion.div
                key={activeFeature}
                initial={{ opacity: 0, scale: 0.98, y: 10 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.98, y: -10 }}
                transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
                className="absolute inset-0 w-full h-full flex items-center justify-center"
              >
                {features[activeFeature].visual}
              </motion.div>
            </AnimatePresence>
            
            {/* Subtle inner shadow overlay to give it depth */}
            <div className="absolute inset-0 shadow-[inset_0_0_40px_rgba(0,0,0,0.02)] pointer-events-none rounded-[32px]" />
          </div>
        </div>
        
      </div>
      
    </section>
  );
}
